name: Results

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm install

  test:
    name: Test project
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:2022
